spring.application.name=vms-mma-platform-api

server.port=${SERVER_PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.application.business-name=VMS-MMA
info.application.technical-name=vms-mma
info.application.service-name=vms-mma-platform-api
info.application.environment=${VMS_MMA_ENVIRONMENT:dev}
info.application.region=${VMS_MMA_AWS_REGION:ap-south-1}
info.application.custom-domain-enabled=false
